# .travis.yml for texlive-source CI building
# Norbert Preining
# Public Domain
#
# This file controls CI testing on Travis-CI 
# https://travis-ci.org/TeX-Live/texlive-source/
# via a git-svn checkout of the TeX Live source directory
# which is pushed to Github
# https://github.com/TeX-Live/texlive-source
# The cron job that does the git svn up and git push is
# running on texlive.info
#

language: c

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - libfontconfig-dev
            - libx11-dev
            - libxmu-dev
            - libxaw7-dev
      before_script: find . -name \*.info -exec touch '{}' \;
      script: ./Build
    - os: linux
      services: docker
      script: docker run -v ${TRAVIS_BUILD_DIR}:/texlive -w /texlive -i -t alpine:3.7 sh -c "apk update; apk add --no-progress bash findutils gcc g++ make perl fontconfig-dev libx11-dev libxmu-dev libxaw-dev; cd texlive; find . -name \*.info -exec touch '{}' \; ; ./Build"

